function initIbiPlot()

screen_size = get(0, 'ScreenSize');
screen_width = screen_size(3);
screen_height = screen_size(4);

h0 = figure('Color',[0.84 0.8 0.73], ...
   'CloseRequestFcn','exitHrv', ...
   'MenuBar','none', ...
   'Name','IBI', ...
   'NumberTitle','off', ...
   'Position',[10 screen_height-870 screen_width-375 400], ...
   'Tag','FigureIbiPlot');
h1 = axes('Parent',h0, ...
   'CameraUpVector',[0 1 0], ...
   'Color','none', ...
   'Position',[0.08 0.11 0.85 0.8], ...
   'Tag','AxesIbiPlot', ...
   'XColor',[0 0 0], ...
   'XGrid','on', ...
   'YColor',[0 0 0], ...
   'YGrid','on');
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'HandleVisibility','off', ...
   'HorizontalAlignment','center', ...
   'Position',[0.50 -0.07 9.16], ...
   'String','Time (sec)', ...
   'Tag','AxesIbiPlotXLabel', ...
   'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'HandleVisibility','off', ...
   'HorizontalAlignment','center', ...
   'Position',[-0.07 0.50 9.16], ...
   'Rotation',90, ...
   'String','IBI (msec)', ...
   'Tag','AxesIbiPlotYLabel', ...
   'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
   'Color',[0 0 0], ...
   'HandleVisibility','off', ...
   'HorizontalAlignment','center', ...
   'Position',[0.50 1.02 9.16], ...
   'String','IBI', ...
   'Tag','AxesIbiPlotTitle', ...
   'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);