library(R.matlab)
library(lavaan)
library(dplyr)
library(lattice)
setwd("/Users/alisonmarie526/Box Sync/DEPENd/Projects/PD_Interaction_Dynamics/output/")
#setwd("~/Desktop")
dt <- readMat("sanitycheck_rawparams.mat")
dtm1 <- as.data.frame(dt$sfrawparamsm1, row.names = as.integer(dt$ids))
dtm2 <- as.data.frame(dt$sfrawparamsm2, row.names = as.integer(dt$ids))
dtm3 <- as.data.frame(dt$sfrawparamsm3, row.names = as.integer(dt$ids))
colnames <- c("self_coupling_patient", "cross_coupling_patient", "self_coupling_partner", "cross_coupling_partner", "p1star", "p2star")
dtm4 <- as.data.frame(dt$sfrawparamsm4, row.names = as.integer(dt$ids))
dtm4 <- dplyr::rename(dtm4,  self_coupling_patient = V1, cross_coupling_patient = V2, self_coupling_partner = V3, cross_coupling_partner = V4, p1star = V5, p2star = V6 )
dtm1 <- dplyr::rename(dtm1,  self_coupling_patient = V1, cross_coupling_patient = V2, self_coupling_partner = V3, cross_coupling_partner = V4, p1star = V5, p2star = V6 )
dtm2 <- dplyr::rename(dtm2,  self_coupling_patient = V1, cross_coupling_patient = V2, self_coupling_partner = V3, cross_coupling_partner = V4, p1star = V5, p2star = V6 )
dtm3 <- dplyr::rename(dtm3,  self_coupling_patient = V1, cross_coupling_patient = V2, self_coupling_partner = V3, cross_coupling_partner = V4, p1star = V5, p2star = V6 )
dtm1nooutliers <- dplyr::filter(dtm1, abs(self_coupling_patient) < .3 & abs(cross_coupling_patient)  < .3 & abs(self_coupling_partner) < .3 & abs(cross_coupling_patient) <.3 )
