library(tidyverse)
sas_params <- read.csv("/Users/ams939/Box Sync/DEPENd/Projects/PD_Interaction_Dynamics/data/sasvsVB/sas_params_var.csv")
df <- read.csv("/Users/ams939/Box Sync/DEPENd/Projects/PD_Interaction_Dynamics/results/fulldata_VAR.csv") %>% dplyr::filter(!is.na(scpt), m1_R2 > .98, PTNUM != 8040, PTNUM != 8048, PTNUM != 8073) %>% dplyr::select(PTNUM, scpt, ccpt, scpr, ccpr)
sas_params <- dplyr::select(sas_params, ptnum, a1, a2, b1, b2) %>% mutate(PTNUM = ptnum) %>% dplyr::select(-ptnum)
sas_params_df <- inner_join(sas_params, df)
round(cor(dplyr::select(sas_params_df, -PTNUM)),3)
sas_params_df_long <- gather(sas_params_df, key = key, value = value, -PTNUM) %>% mutate(vba_sas = if_else(key %in% c("scpt", "ccpt", "scpr", "ccpr"), "VBA","SAS"))%>% mutate(key = case_when(key == "a1" ~ "scpt", key == "a2" ~ "ccpt", key == "b1"~ "scpr", key == "b2" ~ "ccpr", key == "scpt" ~ "scpt", key == "ccpt" ~ "ccpt", key == "scpr"~ "scpr", key == "ccpr" ~ "ccpr")) 
sas_params_df_long_wide <- spread(sas_params_df_long, key = vba_sas, value = value)
ggplot(sas_params_df_long_wide, aes(x=VBA, y= SAS, color = as.factor(key))) + geom_point() + geom_smooth(method = "lm") +scale_color_discrete(name="Coupling Parameter") + ggtitle("SAS vs. VBA Parameterization")