library(R.matlab)
library(lavaan)
library(dplyr)
library(lattice)
setwd("/Users/ams939/Desktop/")
#setwd("~/Desktop")
dt <- readMat("modelcomparison_rawparams.mat")
dtm1 <- as.data.frame(dt$sfrawparamsm1, row.names = as.integer(dt$ids))
dtm2 <- as.data.frame(dt$sfrawparamsm2, row.names = as.integer(dt$ids))
dtm2$id <- as.vector(dt$ids)
dtm3 <- as.data.frame(dt$sfrawparamsm3, row.names = as.integer(dt$ids))
colnames <- c("self_coupling_patient", "cross_coupling_patient", "self_coupling_partner", "cross_coupling_partner", "p1star", "p2star")
dtm4 <- as.data.frame(dt$sfrawparamsm4, row.names = as.integer(dt$ids))
dtm4 <- dplyr::rename(dtm4,  self_coupling_patient = V1, cross_coupling_patient = V2, self_coupling_partner = V3, cross_coupling_partner = V4, p1star = V5, p2star = V6 )
dtm1 <- dplyr::rename(dtm1,  self_coupling_patient = V1, cross_coupling_patient = V2, self_coupling_partner = V3, cross_coupling_partner = V4, p1star = V5, p2star = V6 )
dtm2 <- dplyr::rename(dtm2,  self_coupling_patient = V1, cross_coupling_patient = V2, self_coupling_partner = V3, cross_coupling_partner = V4, p1star = V5, p2star = V6 )
dtm3 <- dplyr::rename(dtm3,  self_coupling_patient = V1, cross_coupling_patient = V2, self_coupling_partner = V3, cross_coupling_partner = V4, p1star = V5, p2star = V6 )
dtm1nooutliers <- dplyr::filter(dtm1, abs(self_coupling_patient) < .3 & abs(cross_coupling_patient)  < .3 & abs(self_coupling_partner) < .3 & abs(cross_coupling_patient) <.3 )
dtm2nooutliers <- dplyr::filter(dtm2, abs(self_coupling_patient) < .3 & abs(cross_coupling_patient)  < .3 & abs(self_coupling_partner) < .3 & abs(cross_coupling_patient) <.3 )
dtm3nooutliers <- dplyr::filter(dtm3, abs(self_coupling_patient) < .3 & abs(cross_coupling_patient)  < .3 & abs(self_coupling_partner) < .3 & abs(cross_coupling_patient) <.3 )
dtm4nooutliers <- dplyr::filter(dtm4, abs(self_coupling_patient) < .3 & abs(cross_coupling_patient)  < .3 & abs(self_coupling_partner) < .3 & abs(cross_coupling_patient) <.3 )
lattice::splom(dplyr::select(dtm1nooutliers, self_coupling_patient, cross_coupling_patient, self_coupling_partner, cross_coupling_partner, p1star, p2star))
lattice::splom(dplyr::select(dtm2nooutliers, self_coupling_patient, cross_coupling_patient, self_coupling_partner, cross_coupling_partner))
lattice::splom(dplyr::select(dtm3nooutliers, self_coupling_patient, cross_coupling_patient, self_coupling_partner, cross_coupling_partner, p1star, p2star))
lattice::splom(dplyr::select(dtm4nooutliers, self_coupling_patient, cross_coupling_patient, self_coupling_partner, cross_coupling_partner))
lattice::splom(dplyr::select(dtm1, self_coupling_patient, cross_coupling_patient, self_coupling_partner, cross_coupling_partner, p1star, p2star))
lattice::splom(dplyr::select(dtm2, self_coupling_patient, cross_coupling_patient, self_coupling_partner, cross_coupling_partner))
lattice::splom(dplyr::select(dtm3, self_coupling_patient, cross_coupling_patient, self_coupling_partner, cross_coupling_partner, p1star, p2star))
lattice::splom(dplyr::select(dtm4, self_coupling_patient, cross_coupling_patient, self_coupling_partner, cross_coupling_partner))


#just to compare to the last sanity check (which would be the 5th model)
sanity_check_params <-readMat("lastsanity_check_rawparams.mat")
sanity_check_params <- as.data.frame(sanity_check_params$sfrawparams[,1,])
sanity_check_params <- dplyr::select(sanity_check_params, V1, V2) %>% dplyr::rename(self_coupling_patient = V1, cross_coupling_patient = V2)
sanity_check_ids <- readMat("lastsanity_check_rawparams.mat")
sanity_check_ids$ids <- as.vector(sanity_check_ids$ids[1,])
sanity_check_params$id <- sanity_check_ids$ids
sanity_check_params <- rename(sanity_check_params, sanity_self_coupling_patient = self_coupling_patient, sanity_cross_coupling_patient = cross_coupling_patient)
ccf <- merge(dtm2nooutliers, sanity_check_params, by = "id")
